config/routes.rb
Rails.application.routes.draw do

  resources :tweets
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root 'epicenter#feed'

  get 'tweets' => 'tweets#index'

  get 'show_user' => 'epicenter#show_user'

  get 'now_following' => 'epicenter#now_following'

  get 'unfollow' => 'epicenter#unfollow'

  get 'tag_tweets' => 'epicenter#tag_tweets'

  get 'all_users' => 'epicenter#all_users'

  get 'following' => 'epicenter#following'

  get 'followers' => 'epicenter#followers'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/tag.rb
class Tag < ApplicationRecord

	has_many :tweet_tags
	has_many :tweets, through: :tweet_tags
end

app/models/tweet.rb
class Tweet < ApplicationRecord
	before_validation :link_check, on: :create

	belongs_to :user

	has_many :tweet_tags
	has_many :tags, through: :tweet_tags



	validates :message, presence: true
	validates :message, length: {maximum: 140, too_long: "Pwease don't say so much! A pweet can only be 140 characters max."}, on: :create

	after_validation :apply_link, on: :create
	
	private

	def link_check
		check = false
		if self.message.include? "http://"
			check = true
		elsif self.message.include? "https://"
			check = true
		else
			check = false
		end

		if check == true
			arr = self.message.split
			index = arr.map{ |x| x.include? "http"}.index(true)
			self.link = arr[index]
			if arr[index].length > 23
				arr[index] = "#{arr[index][0..20]}..."
			end

			self.message = arr.join(" ")
		end
	end

	def apply_link
		arr = self.message.split

		index = arr.map { |x| x.include? "http://" || x.include?("https:.//") }.index(true)

		if index

			url = arr[index]

			arr[index] = "<a href='#{self.link}' target='_blank'>#{url}</a>"
		end

		self.message = arr.join(" ")
	end
end

app/models/tweet_tag.rb
class TweetTag < ApplicationRecord
	belongs_to :tweet 
	belongs_to :tag 
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :tweets, dependent: :destroy
    # this next statement tricks ruby into converting the text value of following to an array
    
  serialize :following, Array


  mount_uploader :avatar, AvatarUploader

  validates :username, presence: true
  validates :username, uniqueness: true



end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

	before_action :configure_permitted_parameters, if: :devise_controller?

	before_action :authenticate_user!
	protected

	def configure_permitted_parameters
		devise_parameter_sanitizer.permit(:sign_up, keys: [:username, :name, :bio, :location, :avatar, :following])
		devise_parameter_sanitizer.permit(:account_update, keys: [:username, :name, :bio, :location, :avatar, :following])
	end



end

app/controllers/epicenter_controller.rb
class EpicenterController < ApplicationController
  def feed

    @currusertweets_array = current_user.tweets
    @curruserfollowing = current_user.following.count
    @following_tweets = []
    @followers = 0
    User.all.each do |user|
      if user.following.include?(current_user.id)
        @followers += 1
      end
    end
  	Tweet.all.each do |tweet|  
  		if current_user.following.include?(tweet.user_id) || current_user.id == tweet.user_id
  			@following_tweets.push(tweet)
  		end
  	end
  end

  def tag_tweets
    @tag = Tag.find(params[:id])
  end

  def all_users
    @users = User.all
  end


  def show_user
  	@user = User.find(params[:id])
    @totaltweets_array = []
    @totaltweets_array = @user.tweets
    @userfollowing = @user.following.count
    @userfollower_array = []
    @userfollowers = 0
    User.all.each do |user|
      if user.following.include?(@user.id)
        @userfollowers += 1
      end
    end

  end

  def now_following

  # We are adding the user.id of the user you want to 
  # follow to your following array.
  # and we want to make sure it's saved in there as an integer
  current_user.following.push(params[:id].to_i)
  current_user.save

  redirect_to show_user_path(id: params[:id])

  end

  def unfollow

  current_user.following.delete(params[:id].to_i)
  current_user.save
# We get this tag fromt the tweets_helper statement at end id=
  redirect_to all_users_path
  end

  def following
    @user = User.find(params[:id])
    @users = []

    User.all.each do |user|
      if @user.following.include?(user.id)
        @users.push(user)
      end
  end
  end

  def followers
    @user = User.find(params[:id])
    @users = []

    User.all.each do |user|
      if user.following.include?(@user.id)
        @users.push(user)
      end
  end
  end



end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController

  before_action :set_tweet, only: [:show, :edit, :update, :destroy]



  include TweetsHelper


  # GET /tweets
  # GET /tweets.json
  def index
    @tweets = Tweet.all

  end

  # GET /tweets/1
  # GET /tweets/1.json
  def show
  end

  # GET /tweets/new
  def new
    @tweet = Tweet.new
  end

  # GET /tweets/1/edit
  def edit
  end

  # POST /tweets
  # POST /tweets.json
  def create
    @tweet = Tweet.create(tweet_params)

    @tweet = get_tagged(@tweet)

    respond_to do |format|
      if @tweet.save
        format.html { redirect_to @tweet, notice: 'Tweet was successfully created.' }
        format.json { render :show, status: :created, location: @tweet }
      else
        format.html { render :new }
        format.json { render json: @tweet.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tweets/1
  # PATCH/PUT /tweets/1.json
  def update
    respond_to do |format|
      if @tweet.update(tweet_params)
        format.html { redirect_to @tweet, notice: 'Tweet was successfully updated.' }
        format.json { render :show, status: :ok, location: @tweet }
      else
        format.html { render :edit }
        format.json { render json: @tweet.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tweets/1
  # DELETE /tweets/1.json
  def destroy
    @tweet.destroy
    respond_to do |format|
      format.html { redirect_to tweets_url, notice: 'Tweet was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tweet
      @tweet = Tweet.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def tweet_params
      params.require(:tweet).permit(:message, :user_id, :link)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/epicenter_helper.rb
module EpicenterHelper
end

app/helpers/tweets_helper.rb
module TweetsHelper
    
    def get_tagged(tweet)
        
    message_arr = Array.new
    message_arr = tweet.message.split
    
    message_arr.each_with_index do |word, index|
      if word[0] == "#"
        if Tag.pluck(:phrase).include?(word.downcase)
          tag = Tag.find_by(phrase: word.downcase)
        else
          tag = Tag.create(phrase: word.downcase)
        end
        
        tweet_tag = TweetTag.create(tweet_id: @tweet.id, tag_id: tag.id)
        
        message_arr[index] = "<a href='/tag_tweets?id=#{tag.id}'>#{word}</a>"
        end
        
    end
    
    tweet.message = message_arr.join(" ")
    #@tweet.update(message: message_arr.join(" "))
    return tweet
    
    end
    
end

app/views/epicenter/_user_list.html.erb
<div class="row">
	<% @users.each_with_index do |user, index| %>
	<div class="col-md-3">
		<div class="well user-list-wells">
			<div class="row">
				<div class="col-md-6">
					<% unless user.avatar.blank? %>
					<%= image_tag user.avatar.url, size: 100 %>
					<% end %>
				</div>
				<div class="col-md-6">
					<p>
						<% if current_user.following.include?(user.id) %>
						<%= link_to "Following", unfollow_path(id: user.id), class: "btn btn-primary", id: "unfollow_btn_#{index}" %>
						<% else %>
							<% if current_user.id != user.id %>
							<%= link_to "Follow", now_following_path(id: user.id), class: " btn btn-primary" %>
							<% end %>
						<% end %>
					</p>
				</div>
			</div>
			<div class="row">
				<%= link_to show_user_path(id: user.id) do %>
				<h3><%= user.name %></h3>
				<p>@<%= user.username %></p>

				<% end %>
			</div>
		</div>
	</div>
	<script>
		$(document).on('turbolinks:load', function() {
			$('#unfollow_btn_<%= index %>').hover(function() {
				$(this).removeClass('btn-primary');
				$(this).addClass('btn-danger');
				$(this).html("Unfollow");
			}, function(){
				$(this).html("Following");
				$(this).removeClass('btn-danger');
				$(this).addClass('btn-primary');
			});
			})


	</script>
	<% end %>
</div>

app/views/epicenter/all_users.html.erb
<%= render 'user_list' %>

app/views/epicenter/feed.html.erb
  <div class="row">
   <div class="col-sm-3"> 
 		<div class="card text-white bg-warning mb-3 text-center" style="max-width: 25rem;">
      <h3 class="card-header"><%= current_user.name %></h3>
     <img class="card-img-top">
  		<%= image_tag current_user.avatar.url, size:180, class: "user-pic-nav" %> 
            <h4 class="card-title">@<%= current_user.username %></h4>
            <div class="card-body">     					
              <table align='center'>
    						<thead>
    							<tr>
    								<th>Pweets</th>
    								<th>Following</th>
    								<th>Followers</th>
    							</tr>
    						</thead>
    						</tbody>
    							<tr>
    								<td><%= @currusertweets_array.count %></td>
    								<td><%= @curruserfollowing %></td>
    								<td><%= @followers %></td>
    							</tr>
    						</body>
    					</table>
  			</div>
		</div>   
    </div> 
    <div class="col-sm-9">
      <h2>@<%= current_user.username %>'s Chattter Feed</h2>       
      <div class="well">
	
		<% @following_tweets.reverse.each do |tweet| %>
     		
          <div class="panel panel-default">
 	 			    <div class="panel-heading">
 	 				     <%= image_tag tweet.user.avatar.url, size:25, class: "tweeter-pic-nav" %> 
 	 				     @<%= link_to tweet.user.username, show_user_path(id: tweet.user.id) %>&nbsp&nbsp 
                <em>Posted <%= time_ago_in_words(tweet.created_at) %>&nbspago</em>
 	 					
 	 				 </div>
 	 			  <div class="panel-body"><%= tweet.message.html_safe %></div>
        </div>
		
		<% end %>

      </div>
    </div>
  </div>

app/views/epicenter/followers.html.erb
<h1><%= @user.name %>'s Followers</h1>

<%= render 'user_list' %>

app/views/epicenter/following.html.erb
<h1><%= @user.name %> is Following</h1>

<%= render 'user_list' %>

app/views/epicenter/now_follow.html.erb
<h1>Epicenter#now_follow</h1>
<p>Find me in app/views/epicenter/now_follow.html.erb</p>

app/views/epicenter/show_user.html.erb
<h1> @<%= @user.username %>'s Profile and Pweets</h1>
<div class="container">
<div class="row">
<div class="col-sm-3">
<div class="card text-white bg-warning mb-3 text-center" style="max-width: 18rem;">
	<p><%= image_tag @user.avatar.url, size:180, class: "user-pic-nav" %> </p>
	<% if current_user.following.include?(@user.id) %>
		<p align='center'><%= link_to "Following", unfollow_path(id: @user.id), class: "btn btn-primary", id: "unfollow_btn" %></p>
	<% else %>
		<% if current_user.id != @user.id %>
			<p align='center'><%= link_to "Follow", now_following_path(id: @user.id), class: "btn btn-primary" %></p>
		<% end %>
	<% end %>
	 <div class="card-body">
		<h5 class="card-title"><strong><%= @user.name %></strong></h5>
		<h4 class="card-title">@<%= @user.username %></h4>
		<p class="card-text">Owner:<%= @user.location%><br/><%= @user.bio %></p>
		<%= link_to "Followers", followers_path(id: @user.id), class: "btn btn-default" %>
		<%= link_to "Following", following_path(id: @user.id), class: "btn btn-default" %>

			<table>
				<thead>
					<tr>
						<th>Pweets</th>
						<th>Following</th>
						<th>Followers</th>
					</tr>
				</thead>
				</tbody>
					<tr>
						<td align='center'><%= @totaltweets_array.count %></td>
						<td align='center'><%= @userfollowing %></td>
						<td align='center'><%= @userfollowers %></td>
					</tr>
				</body>
			</table>
	</div>	
</div>   

 </div>
   <div class="col-sm-9">
     <h2>@<%= @user.username %>'s Pitter Chatter</h2>   	
	<% @user.tweets.reverse.each do |tweet| %>
     	<div class="panel panel-default">
 	 		<div class="panel-heading"><em>Posted <%= time_ago_in_words(tweet.created_at) %>&nbspago</em></div>
 	 		<div class="panel-body">
 	 			<%= tweet.message.html_safe %></div>

 		</div>
 	 <%end %>		
	</div>
 </div>
</div>

app/views/epicenter/tag_tweets.html.erb
<div>
    <h1>Chatter about <%= @tag.phrase %></h1>
</div>

<div class="well">
<div class="row">
    
    <div>
        <% @tag.tweets.order(created_at: :desc).each do |tweet| %>
        <p>
            <%= image_tag tweet.user.avatar.url, size:25, class: "tweeter-pic-nav" %> 
            <%= tweet.user.name %> <%= "@#{tweet.user.username}" %>
            • <%= time_ago_in_words(tweet.created_at) %> ago
        </p>
        
            <p>&nbsp&nbsp&nbsp&nbsp
                <%= tweet.message.html_safe %>
            </p>
            <hr>
    <% end %>
    </div>
</div>
</div>

app/views/epicenter/unfollow.html.erb
<h1>Epicenter#unfollow</h1>
<p>Find me in app/views/epicenter/unfollow.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PitterChat</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

<!-- app/views/layouts/application.html.erb -->
<body  { padding-top: 70px; }>

<div>
  <nav class="navbar navbar-light " style="background-color: #e3f2fd;">
    <div class="container-fluid">
      <!-- Brand and toggle get grouped for better mobile display -->
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <%= link_to "PitterChat", root_path, class: "navbar-brand" %>
      </div>
      <!-- Collect the nav links, forms, and other content for toggling -->
      <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
        <ul class="nav navbar-nav">
          <li><%= link_to "Pitter some Chatter", new_tweet_path %></li>
          <li><%= link_to "All Critters", all_users_path %></li>
          <li><strong>.........BECAUSE CRITTERS NEED TO TWITTER TOO...</strong></li>
        </ul>
        <ul class="nav navbar-nav navbar-right">
          <% if user_signed_in? %>
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
                <% if current_user.avatar.blank? == false %>
                  <%= image_tag current_user.avatar.url, size:50, class: "user-pic-nav" %>
                <% end %>
                @<%= current_user.username %> <span class="caret"></span></a>
              <ul class="dropdown-menu">
                <li><%= link_to "Edit Profile", edit_user_registration_path %></li>
                <li><%= link_to "Sign Out", destroy_user_session_path, method: :delete %></li>
              </ul>
            </li>
          <% end %>
        </ul>
      </div>
    </div>
  </nav>
</div>
	<div class="container">
    <%= yield %>
	</div>
</body>
</html>

app/views/tweets/_form.html.erb
<%= form_with(model: tweet, local: true) do |form| %>
  <% if tweet.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(tweet.errors.count, "error") %> prohibited this tweet from being saved:</h2>

      <ul>
      <% tweet.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

<!-- you could also use 
-->
  <div class="field">
    <%= form.label :Pweet %><br />
    <%= form.text_area :message %>
  </div>
<!-- we don't want user id to show but still need to capture it for every new tweet so we make it hidden -->
  <div class="field">  
    <%= form.hidden_field :user_id, value: current_user.id %>
  </div>

  <div class="actions">
    <%= form.submit "Pweet It!", class: "btn btn-primary" %>
  </div>
<% end %>

app/views/tweets/edit.html.erb
<h1>Editing Tweet</h1>

<%= render 'form', tweet: @tweet %>

<%= link_to 'Show', @tweet %> |
<%= link_to 'Back', tweets_path %>

app/views/tweets/index.html.erb
<p id="notice"><%= notice %></p>

<h1>PitterChatter</h1>

<table>
  <thead>
    <tr>
      <th>Pweet</th>
      <th>Pitterer</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @tweets.reverse.each do |tweet| %>
      <tr>
        <td><%= tweet.message.html_safe %></td>
        <td><%= link_to tweet.user.username, show_user_path(id: tweet.user.id) %></td>
        <td><%= link_to 'Show', tweet %></td>
        <td><%= link_to 'Edit', edit_tweet_path(tweet) %></td>
        <td><%= link_to 'Destroy', tweet, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Pitter', new_tweet_path %>

app/views/tweets/new.html.erb
<h1>Pitter some new Chatter!</h1>

<%= render 'form', tweet: @tweet %>

<%= link_to 'Back', tweets_path %>

app/views/tweets/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Pittering...:</strong>
  <%= @tweet.message.html_safe %>
</p>

<p>
  <strong>User:</strong>
  @<%= link_to @tweet.user.username, show_user_path(id: @tweet.user.id) %>
</p>

<%= link_to 'Edit', edit_tweet_path(@tweet) %> |
<%= link_to 'Back', tweets_path %>